[build]
  command = "npm test && npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/portal-sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
